FROM ubuntu:16.04 

WORKDIR /usr/src/app
COPY ./PART-01/1.14/example-frontend . 

EXPOSE 5000
ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN apt-get update &&\
    apt-get install -y curl xsel &&\
    curl -sL https://deb.nodesource.com/setup_14.x | bash &&\
    apt install -y nodejs

RUN npm install 
RUN npm run build 
RUN npm install -g serve 

CMD ["serve", "-s", "-l", "5000", "build"]